receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  kafkametrics:
    brokers:
      - kafka:9093
    protocol_version: 2.0.0
    scrapers:
      - brokers
      - topics
      - consumers
    collection_interval: 30s

processors:
  batch: {}
  resource:
    attributes:
      - key: deployment.environment
        value: dev
        action: upsert

exporters:
  otlp_grpc/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  otlp_grpc/dash0:
    endpoint: ${env:DASH0_OTLP_ENDPOINT}
    headers:
      Authorization: "Bearer ${env:DASH0_AUTH_TOKEN}"
      Dash0-Dataset: "${env:DASH0_DATASET}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp_grpc/jaeger, otlp_grpc/dash0]
    metrics:
      receivers: [otlp, kafkametrics]
      processors: [resource, batch]
      exporters: [otlp_grpc/dash0]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp_grpc/dash0]
